function AddSystem(hObject,handles)
%AddSystem(hObject,handles)
%Adds a system to the plant.

global Plant Model_dir SYSINDEX
nG = length(Plant.Generator);
SYSINDEX = nG+1;
emptyStr = '[None]';
files=dir(fullfile(Model_dir,'System Library',get(hObject,'Tag'),'*.mat'));
list=strrep({files.name},'.mat','');
if isempty(list)
    list{1} = emptyStr;
end
[s,OK] = listdlg('PromptString','Select Model', ...
    'SelectionMode','single', ...
    'ListString',list);
if OK && ~strcmp(list{s},emptyStr)
    componentName = list{s};
    load(fullfile(Model_dir,'System Library',get(hObject,'Tag'), ...
        strcat(componentName,'.mat')));
    if strcmp(component.Type,'Utility')
        Plant.Generator(SYSINDEX) = struct( ...
            'Type',component.Type, ...
            'Name','Elec Utility1', ...
            'Source','Electricity', ...
            'Output',struct('Capacity',[], ...
                'Electricity',[], ...
                'Heat',[], ...
                'Steam',[], ...
                'Cooling',[]), ...
            'Size',1, ...
            'Enabled',1, ...
            'VariableStruct',rmfield(component, {'Type','Source'}));
    else
        Plant.Generator(SYSINDEX) = component;
    end
    Plant.Network(1).Equipment(end+1) = {strcat( ...
        Plant.Generator(SYSINDEX).Type,'.',Plant.Generator(SYSINDEX).Name)};
    EditSystem(handles)
end
updateSystemRep(hObject,[], handles)
