function [fitresult, gof] = createFit(pf, hop)
%CREATEFIT(PF,HOP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : pf
%      Y Output: hop
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Jan-2013 09:54:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( pf, hop );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'hop vs. pf', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'pf' );
% ylabel( 'hop' );
% grid on


